export enum USER_EVENTS {
    USER_JOIN_REQUEST = 'USER.JOIN.REQUEST',
    USER_JOINED = 'USER.JOINED',
    USER_DISCONNECT = 'USER.DISCONNECT',
    USER_LEFT = 'USER.LEFT',


}

export enum CHAT_EVENTS {
    CHAT_MESSAGE = 'CHAT.MESSAGE',
    CHAT_MESSAGE_RECEIVED = 'CHAT.MESSAGE.RECEIVED',
}